version: "3"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: node_postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data # Corrected volume definition
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  db: # Define the volume named 'db' here
